// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	Code   int64         `json:"code"`
	Msg    string        `json:"msg"`
	Status string        `json:"status"`
	Data   UserLoginData `json:"data"`
}

type UserLoginData struct {
	UserNo int64  `json:"userNo"`
	Mobile string `json:"mobile"`
	Token  string `json:"token"`
}

type UserListReq struct {
	Current  int64  `json:"current,default=1"`
	PageSize int64  `json:"pageSize,default=20"`
	Mobile   string `json:"mobile,optional"`
	StatusID string `json:"statusId,optional"`
}

type UserListResp struct {
	Code     int64      `json:"code"`
	Msg      string     `json:"msg"`
	Data     []UserList `json:"data"`
	Current  int64      `json:"current,default=1"`
	PageSize int64      `json:"pageSize,default=20"`
	Success  bool       `json:"success"`
	Total    int64      `json:"total"`
}

type UserList struct {
	Id         int64  `json:"id"`
	StatusID   int64  `json:"statusId"`
	Sort       int64  `json:"sort"`
	UserNo     int64  `json:"userNo"`
	Mobile     string `json:"mobile"`
	RealName   string `json:"realName"`
	Remark     string `json:"remark"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type UserViewReq struct {
	Id int64 `json:"id"`
}

type UserViewResp struct {
	Code int64        `json:"code"`
	Msg  string       `json:"msg"`
	Data UserViewData `json:"data"`
}

type UserViewData struct {
	Id       int64  `json:"id"`
	StatusID int64  `json:"statusId"`
	Sort     int64  `json:"sort"`
	UserNo   int64  `json:"userNo"`
	Mobile   string `json:"mobile"`
	RealName string `json:"realName"`
	Remark   string `json:"remark"`
}

type UserSaveReq struct {
	Mobile   string `json:"mobile"`
	RealName string `json:"realName"`
	Remark   string `json:"remark"`
}

type UserSaveResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type UserUpdateReq struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	RealName string `json:"realName"`
	Remark   string `json:"remark"`
	StatusID int64  `json:"statusId"`
	Sort     int64  `json:"sort"`
}

type UserUpdateResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type UserStatusUpdateReq struct {
	Id       int64 `json:"id"`
	StatusID int64 `json:"statusId"`
}

type UserStatusUpdateResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type UserDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type UserDeleteResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type UserUpdatePasswordReq struct {
	Id        int64  `json:"id"`
	MobilePsw string `json:"mobilePsw"`
	RePwd     string `json:"rePwd"`
}

type UserUpdatePasswordResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type RoleListReq struct {
	Current  int64  `json:"current,default=1"`
	PageSize int64  `json:"pageSize,default=20"`
	StatusID string `json:"statusId,optional"`
	RoleName string `json:"roleName,optional"`
}

type RoleListResp struct {
	Code     int64      `json:"code"`
	Msg      string     `json:"msg"`
	Data     []RoleList `json:"data"`
	Current  int64      `json:"current,default=1"`
	PageSize int64      `json:"pageSize,default=20"`
	Success  bool       `json:"success"`
	Total    int64      `json:"total"`
}

type RoleList struct {
	Id         int64  `json:"id"`
	StatusID   int64  `json:"statusId"`
	Sort       int64  `json:"sort"`
	RoleName   string `json:"roleName"`
	Remark     string `json:"remark"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type RoleViewReq struct {
	Id int64 `json:"id"`
}

type RoleViewResp struct {
	Code int64        `json:"code"`
	Msg  string       `json:"msg"`
	Data RoleViewData `json:"data"`
}

type RoleViewData struct {
	Id       int64  `json:"id"`
	StatusID int64  `json:"statusId"`
	Sort     int64  `json:"sort"`
	RoleName string `json:"roleName"`
	Remark   string `json:"remark"`
}

type RoleSaveReq struct {
	RoleName string `json:"roleName"`
	Remark   string `json:"remark"`
	Sort     string `json:"sort"`
}

type RoleSaveResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type RoleUpdateReq struct {
	Id       int64  `json:"id"`
	RoleName string `json:"roleName"`
	Remark   string `json:"remark"`
	StatusID int64  `json:"statusId"`
	Sort     int64  `json:"sort"`
}

type RoleUpdateResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type RoleStatusUpdateReq struct {
	Id       int64 `json:"id"`
	StatusID int64 `json:"statusId"`
}

type RoleStatusUpdateResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type RoleDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type RoleDeleteResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type RoleUserListReq struct {
	UserId int64 `json:"userId"`
}

type RoleUserListResp struct {
	Code int64            `json:"code"`
	Msg  string           `json:"msg"`
	Data RoleUserListData `json:"data"`
}

type RoleUserListData struct {
	AllRoles       []RoleUserList `json:"allRoles"`
	AllUserRoleIds []int64        `json:"allUserRoleIds"`
}

type RoleUserList struct {
	Id         int64  `json:"id"`
	StatusID   int64  `json:"statusId"`
	Sort       int64  `json:"sort"`
	RoleName   string `json:"roleName"`
	Remark     string `json:"remark"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type RoleUserSaveReq struct {
	UserId int64   `json:"userId"`
	RoleId []int64 `json:"roleId"`
}

type RoleUserSaveResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type MenuListReq struct {
	MenuName string `json:"menuName,optional"`
}

type MenuListResp struct {
	Code int64      `json:"code"`
	Msg  string     `json:"msg"`
	Data []MenuList `json:"data"`
}

type MenuList struct {
	Id         int64  `json:"id"`
	StatusID   int64  `json:"statusId"`
	Sort       int64  `json:"sort"`
	ParentID   int64  `json:"parentId"`
	MenuName   string `json:"menuName"`
	Label      string `json:"label"`
	MenuURL    string `json:"menuUrl"`
	Icon       string `json:"icon"`
	ApiUrl     string `json:"apiUrl"`
	Remark     string `json:"remark"`
	MenuType   int64  `json:"menuType"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type MenuViewReq struct {
	Id int64 `json:"id"`
}

type MenuViewResp struct {
	Code int64        `json:"code"`
	Msg  string       `json:"msg"`
	Data MenuViewData `json:"data"`
}

type MenuViewData struct {
	Id       int64  `json:"id"`
	StatusID int64  `json:"statusId"`
	Sort     int64  `json:"sort"`
	ParentID int64  `json:"parentId"`
	MenuName string `json:"menuName"`
	Label    string `json:"label"`
	MenuURL  string `json:"menuUrl"`
	ApiUrl   string `json:"apiUrl"`
	Remark   string `json:"remark"`
	MenuType int64  `json:"menuType"`
}

type MenuSaveReq struct {
	MenuName string `json:"menuName"`
	MenuType int64  `json:"menuType"`
	MenuUrl  string `json:"menuUrl"`
	StatusId int64  `json:"statusId,default=1"`
	ParentId int64  `json:"parentId,default=0"`
	Remark   string `json:"remark"`
	Sort     int64  `json:"sort"`
	Icon     string `json:"icon"`
}

type MenuSaveResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type MenuUpdateReq struct {
	Id       int64  `json:"id"`
	StatusId int64  `json:"statusId"`
	Sort     int64  `json:"sort"`
	ParentId int64  `json:"parentId"`
	MenuName string `json:"menuName"`
	MenuUrl  string `json:"menuUrl"`
	Icon     string `json:"icon"`
	ApiUrl   string `json:"apiUrl"`
	Remark   string `json:"remark"`
	MenuType int64  `json:"menuType"`
}

type MenuUpdateResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type MenuStatusUpdateReq struct {
	Id       int64 `json:"id"`
	StatusID int64 `json:"statusId"`
}

type MenuStatusUpdateResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type MenuDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type MenuDeleteResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type MenuRoleListReq struct {
	RoleId int64 `json:"roleId"`
}

type MenuRoleListResp struct {
	Code int64            `json:"code"`
	Msg  string           `json:"msg"`
	Data MenuRoleListData `json:"data"`
}

type MenuRoleList struct {
	Id       int64  `json:"id"`
	ParentID int64  `json:"parentId"`
	Title    string `json:"title"`
	Key      string `json:"key"`
}

type MenuRoleListData struct {
	RoleMenus    []int64        `json:"roleMenus"`
	MenuRoleList []MenuRoleList `json:"menuRoleList"`
}

type MenuRoleSaveReq struct {
	MenuIds []int64 `json:"menuIds"`
	RoleId  int64   `json:"roleId"`
}

type MenuRoleSaveResp struct {
	Timestamp string `json:"timestamp"`
	Path      string `json:"path"`
	Status    int64  `json:"status"`
	Error     string `json:"error"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
	Code      int64  `json:"code"`
	Msg       string `json:"msg"`
}

type MenuUserListResp struct {
	Code int64        `json:"code"`
	Msg  string       `json:"msg"`
	Data MenuUserData `json:"data"`
}

type MenuUserData struct {
	SysMenu []MenuUserList `json:"sysMenu"`
	BtnMenu []string       `json:"btnMenu"`
	Avatar  string         `json:"avatar"`
	Name    string         `json:"name"`
}

type MenuUserList struct {
	Id       int64  `json:"id"`
	ParentId int64  `json:"parentId"`
	Name     string `json:"name"`
	Path     string `json:"path"`
	ApiUrl   string `json:"apiUrl"`
	MenuType int64  `json:"menuType"`
	Icon     string `json:"icon"`
}

type EnumReq struct {
	EnumName string `json:"enumName"`
}

type EnumResp struct {
	Code int64      `json:"code"`
	Msg  string     `json:"msg"`
	Data []EnumData `json:"data"`
}

type EnumData struct {
	Code  int64  `json:"code"`
	Color string `json:"color"`
	Name  string `json:"name"`
	Desc  string `json:"desc"`
}
